name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pnpm install
          echo "Dependencies installed successfully"

      - name: Build
        run: |
          echo "Building project..."
          pnpm build
          echo "Build completed"
          ls -la dist/public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/public
          force_orphan: true
          keep_files: true
          clean: true
          publish_branch: gh-pages
          commit_message: 'Deploy to GitHub Pages'
          publish_message: 'Deploy to GitHub Pages'
          domain: 'aumpatel001.github.io'
          custom_domain: 'aumpatel001.github.io'
          cname: 'aumpatel001.github.io'
          keep_history: true
          verbose: true
